---
- name: Create www directory to contain CakePHP code
  command: mkdir -p /vagrant/www/ creates=/vagrant/www

- name: Deploying CakePHP 2.x
  command: composer -sdev -n create-project friendsofcake/app-template . chdir=/vagrant/www/ creates=/vagrant/www/app
  when: cakephp_version == "2"

- name: Deploying CakePHP 3.x
  command: composer -sdev -n create-project cakephp/app . chdir=/vagrant/www/ creates=/vagrant/www/app
  when: cakephp_version == "3"