---
- name: Add APT Key
  apt_key: url="http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1C4CBDCDCD2EFD2A"

- name: Add APT Repository
  apt_repository: repo="deb http://repo.percona.com/apt precise main"

- name: Add APT Source Repository
  apt_repository: repo="deb-src http://repo.percona.com/apt precise main"

- name: Install Percona Server and Client
  apt: pkg={{ item }} state=present
  with_items:
    - percona-server-common-5.5
    - percona-server-server-5.5
    - percona-server-client-5.5

- name: Start Percona Server
  service: name=mysql state=started enabled=true