---
- name: Add PPA
  apt_repository: repo="ppa:ondrej/php5"

- name: Install PHP and Dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - php5-fpm
    - php5-cli
    - php5-common
    - php5-curl
    - php5-gd
    - php5-geoip
    - php5-gmp
    - php5-imagick
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-memcache
    - php5-memcached
    - php5-redis
    - php5-mysql
    - php5-xdebug
    - php5-sqlite
    - php-apc
    - php-pear
    - phpunit

- name: Install Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755 validate_certs=no

- name: Copy pool configuration
  template: src=www.conf dest=/etc/php5/fpm/pool.d/
  notify: restart php-fpm

- name: Start php-fpm
  service: name=php5-fpm state=started enabled=true

  name: Set permissions on /var/lib/php5 to ensure webserver session reading/writing
  file: path=/var/lib/php5 mode=0775 owner=root group=www-data state=directory
