---
- name: Debconf for phpMyAdmin
  debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

- name: Debconf for phpMyAdmin
  debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='' vtype='password'

- name: Debconf for phpMyAdmin
  debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='' vtype='password'

- name: Debconf for phpMyAdmin
  debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='' vtype='password'

- name: Debconf for phpMyAdmin
  debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

- name: Install phpMyAdmin
  apt: pkg=phpmyadmin state=present

- name: Copy AllowEmptyPassword configuration
  template: src=config.inc.php dest=/etc/phpmyadmin/config.inc.php
